project:
  type: website
  output-dir: docs

website:
  title: "Scaling aquatic metabolism across river networks"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: index.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

